a=input('enter 4 digits number=')
print('sorter number:',''.join(sorted(a)))
print('reverse nymber:',a[::-1] )
a_list=list(a)
b=int(a_list[0])
c=int(a_list[1])
d=int(a_list[2])
e=int(a_list[3])
print('multiplied digits:',b*c*d*e)
